# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: stripesfensky/ballcrawl

media_folder: /public/media
public_folder: /media

collections:
  - name: content
    folder: content
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: richtext }
