# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: stripesfensky/ballcrawl
  base_url: https://www.ballcrawl.org

publish_mode: editorial_workflow

media_folder: /public/media
public_folder: /media

collections:
  - name: brands
    label: Brands
    label_singular: Brand
    folder: /content/brands
    fields:
      - { label: Title, name: title, widget: string }
